"""P0 initial schema: full data model

Revision ID: 1c1fc8f7fc96
Revises: 
Create Date: 2026-09-06 16:20:37.069660

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import learningj.db.types


revision: str = '1c1fc8f7fc96'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_import_runs',
    sa.Column('archive_hash', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'done', 'failed', name='dictionary_import_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('stats', learningj.db.types.JsonDictOf(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictionary_import_runs'))
    )
    with op.batch_alter_table('dictionary_import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionary_import_runs_archive_hash'), ['archive_hash'], unique=False)

    op.create_table('dictionary_sources',
    sa.Column('format', sa.Enum('yomitan_zip', name='dictionary_source_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=255), nullable=False),
    sa.Column('archive_hash', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('license_metadata', learningj.db.types.JsonDictOf(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictionary_sources')),
    sa.UniqueConstraint('archive_hash', name=op.f('uq_dictionary_sources_archive_hash'))
    )
    op.create_table('knowledge_points',
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('anchor', sa.String(length=512), nullable=False),
    sa.Column('anchor_shape', sa.Enum('pattern', 'lexical', 'entity', 'opaque', name='anchor_shape', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('anchor_payload', sa.JSON(), nullable=False),
    sa.Column('pattern_grammar_version', sa.String(length=64), nullable=True),
    sa.Column('opaque_reason', sa.Enum('model_chosen', 'validation_failed', name='opaque_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('zero_slot_lexeme_check', sa.JSON(), nullable=True),
    sa.Column('display_form', sa.String(length=512), nullable=True),
    sa.Column('tags', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('retention', sa.Enum('srs', 'reference', name='kp_retention', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('retention_set_by', sa.Enum('default', 'user', name='kp_retention_set_by', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('canonical_id', sa.Uuid(), nullable=True),
    sa.Column('lexical_anchors', learningj.db.types.JsonListOf(), nullable=True),
    sa.Column('origin', sa.Enum('extraction', 'manual', name='kp_origin', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("anchor_shape != 'pattern' OR pattern_grammar_version IS NOT NULL", name=op.f('ck_knowledge_points_pattern_has_grammar_version')),
    sa.CheckConstraint("anchor_shape != 'opaque' OR opaque_reason IS NOT NULL", name=op.f('ck_knowledge_points_opaque_has_reason')),
    sa.ForeignKeyConstraint(['canonical_id'], ['knowledge_points.kp_id'], name=op.f('fk_knowledge_points_canonical_id_knowledge_points')),
    sa.PrimaryKeyConstraint('kp_id', name=op.f('pk_knowledge_points')),
    sa.UniqueConstraint('anchor', name=op.f('uq_knowledge_points_anchor'))
    )
    op.create_table('learner_profile_notes',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Enum('agent', 'user', name='note_updated_by', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_profile_notes'))
    )
    op.create_table('lexemes',
    sa.Column('lexeme_id', sa.String(length=80), nullable=False),
    sa.Column('normalized_form', sa.String(length=512), nullable=False),
    sa.Column('pos', sa.String(length=255), nullable=False),
    sa.Column('reading_form', sa.String(length=512), nullable=False),
    sa.Column('first_seen_analyzer_dict_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lexeme_id', name=op.f('pk_lexemes')),
    sa.UniqueConstraint('normalized_form', 'pos', 'reading_form', name=op.f('uq_lexemes_normalized_form'))
    )
    op.create_table('materials',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('locator', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.Enum('subtitle_video', 'subtitle_audio', 'text', 'epub', name='material_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('copy_stored', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_content_hash'), ['content_hash'], unique=False)

    op.create_table('aliases',
    sa.Column('alias_string', sa.String(length=512), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('seed', 'extraction', 'merge', 'manual', name='alias_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.kp_id'], name=op.f('fk_aliases_kp_id_knowledge_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases')),
    sa.UniqueConstraint('kp_id', 'alias_string', name=op.f('uq_aliases_kp_id'))
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_kp_id'), ['kp_id'], unique=False)

    op.create_table('annotations',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_annotations_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations'))
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_material_id'), ['material_id'], unique=False)

    op.create_table('dictionary_assets',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['dictionary_sources.id'], name=op.f('fk_dictionary_assets_source_id_dictionary_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictionary_assets')),
    sa.UniqueConstraint('source_id', 'relative_path', name=op.f('uq_dictionary_assets_source_id'))
    )
    with op.batch_alter_table('dictionary_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionary_assets_source_id'), ['source_id'], unique=False)

    op.create_table('dictionary_entries',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('expression', sa.String(length=512), nullable=False),
    sa.Column('reading', sa.String(length=512), nullable=True),
    sa.Column('tags', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('source_local_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['dictionary_sources.id'], name=op.f('fk_dictionary_entries_source_id_dictionary_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictionary_entries')),
    sa.UniqueConstraint('source_id', 'source_local_id', name=op.f('uq_dictionary_entries_source_id'))
    )
    with op.batch_alter_table('dictionary_entries', schema=None) as batch_op:
        batch_op.create_index('ix_dictionary_entries_source_expression', ['source_id', 'expression'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionary_entries_source_id'), ['source_id'], unique=False)

    op.create_table('known_evidence',
    sa.Column('lexeme_id', sa.String(length=80), nullable=False),
    sa.Column('conjugated_form', sa.String(length=512), nullable=True),
    sa.Column('source', sa.Enum('reading_inferred', 'analysis_marked', 'import_anki', 'import_jpdb', 'srs_matured', 'listening_native', 'listening_tts', name='known_evidence_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analyzer_dict_version', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_known_evidence_confidence_range')),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.lexeme_id'], name=op.f('fk_known_evidence_lexeme_id_lexemes')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_known_evidence_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_known_evidence'))
    )
    with op.batch_alter_table('known_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_evidence_lexeme_id'), ['lexeme_id'], unique=False)

    op.create_table('sentences',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('time_start', sa.Integer(), nullable=True),
    sa.Column('time_end', sa.Integer(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('anchor_type', sa.Enum('subtitle', 'plain_text', 'epub', name='sentence_anchor_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('anchor_payload', learningj.db.types.JsonDictOf(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_sentences_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentences')),
    sa.UniqueConstraint('material_id', 'index', name=op.f('uq_sentences_material_id'))
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_material_id'), ['material_id'], unique=False)

    op.create_table('sidecars',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('segmenter_version', sa.String(length=255), nullable=False),
    sa.Column('tokenizer_version', sa.String(length=255), nullable=False),
    sa.Column('analyzer_dict_version', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_sidecars_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sidecars'))
    )
    with op.batch_alter_table('sidecars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sidecars_material_id'), ['material_id'], unique=False)

    op.create_table('analyses',
    sa.Column('sentence_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=255), nullable=False),
    sa.Column('style_modules', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('style_free_text', sa.Text(), nullable=True),
    sa.Column('user_question', sa.Text(), nullable=True),
    sa.Column('context_kp_ids', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('context_note_ids', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('retrieval_enabled', sa.Boolean(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('session_closed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='analysis_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('extraction_status', sa.Enum('pending', 'running', 'done', 'failed', name='analysis_extraction_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('extraction_trigger', sa.Enum('user', 'batch', 'background', name='analysis_extraction_trigger', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status != 'generating' OR extraction_status = 'pending'", name=op.f('ck_analyses_generating_implies_extraction_pending')),
    sa.CheckConstraint('turn_count >= 1', name=op.f('ck_analyses_turn_count_positive')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_analyses_material_id_materials')),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_analyses_sentence_id_sentences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_sentence_id'), ['sentence_id'], unique=False)

    op.create_table('dictionary_definitions',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('structured_content', learningj.db.types.JsonDictOf(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['dictionary_entries.id'], name=op.f('fk_dictionary_definitions_entry_id_dictionary_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictionary_definitions')),
    sa.UniqueConstraint('entry_id', 'ordinal', name=op.f('uq_dictionary_definitions_entry_id'))
    )
    with op.batch_alter_table('dictionary_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionary_definitions_entry_id'), ['entry_id'], unique=False)

    op.create_table('material_notes',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_sentence_id', sa.Uuid(), nullable=True),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Enum('agent', 'user', name='note_updated_by', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_notes_material_id_materials')),
    sa.ForeignKeyConstraint(['source_sentence_id'], ['sentences.id'], name=op.f('fk_material_notes_source_sentence_id_sentences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_notes'))
    )
    with op.batch_alter_table('material_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_notes_material_id'), ['material_id'], unique=False)

    op.create_table('spans',
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('sentence_id', sa.Uuid(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('token_start', sa.Integer(), nullable=True),
    sa.Column('token_end', sa.Integer(), nullable=True),
    sa.Column('alignment_status', sa.Enum('aligned', 'partial', 'ambiguous', 'unaligned', name='alignment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('char_start >= 0 AND char_end > char_start', name=op.f('ck_spans_char_range')),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_spans_sentence_id_sentences')),
    sa.PrimaryKeyConstraint('span_id', name=op.f('pk_spans'))
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spans_sentence_id'), ['sentence_id'], unique=False)

    op.create_table('analysis_messages',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='analysis_message_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('turn_index >= 1', name=op.f('ck_analysis_messages_turn_index_positive')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_messages_analysis_id_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_messages')),
    sa.UniqueConstraint('analysis_id', 'turn_index', 'role', name=op.f('uq_analysis_messages_analysis_id'))
    )
    with op.batch_alter_table('analysis_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_messages_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('analysis_sections',
    sa.Column('section_version_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('heading_path', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('split_strategy', sa.Enum('heading', 'paragraph', 'fallback_single', name='analysis_section_split_strategy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('kind', sa.Enum('overview', 'lexical', 'conjugation', 'grammar', 'particle', 'colloquial', 'register', 'culture', 'translation_note', 'takeaway', 'qa', name='analysis_section_kind', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('origin_turn', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_analysis_sections_revision_positive')),
    sa.CheckConstraint('superseded_by IS NULL OR superseded_by != section_version_id', name=op.f('ck_analysis_sections_superseded_not_self')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_sections_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['superseded_by'], ['analysis_sections.section_version_id'], name=op.f('fk_analysis_sections_superseded_by_analysis_sections')),
    sa.PrimaryKeyConstraint('section_version_id', name=op.f('pk_analysis_sections')),
    sa.UniqueConstraint('section_id', 'revision', name=op.f('uq_analysis_sections_section_id'))
    )
    with op.batch_alter_table('analysis_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_sections_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('annotation_spans',
    sa.Column('annotation_id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_annotation_spans_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], name=op.f('fk_annotation_spans_annotation_id_annotations')),
    sa.ForeignKeyConstraint(['span_id'], ['spans.span_id'], name=op.f('fk_annotation_spans_span_id_spans')),
    sa.PrimaryKeyConstraint('annotation_id', 'span_id', name=op.f('pk_annotation_spans')),
    sa.UniqueConstraint('annotation_id', 'ordinal', name=op.f('uq_annotation_spans_annotation_id'))
    )
    op.create_table('extraction_runs',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('execution_path', sa.Enum('continued_turn', 'standalone', name='extraction_run_execution_path', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('running', 'done', 'failed', name='extraction_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('retry_of', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.Enum('invalid_json', 'empty_candidates', 'all_unresolved', 'provider_error', name='extraction_failure_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('unresolved_surfaces', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status = 'running' OR finished_at IS NOT NULL", name=op.f('ck_extraction_runs_finished_runs_have_finished_at')),
    sa.CheckConstraint('candidate_count >= 0', name=op.f('ck_extraction_runs_candidate_count_nonnegative')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_extraction_runs_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['retry_of'], ['extraction_runs.id'], name=op.f('fk_extraction_runs_retry_of_extraction_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_runs_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('analysis_section_spans',
    sa.Column('section_version_id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_analysis_section_spans_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['section_version_id'], ['analysis_sections.section_version_id'], name=op.f('fk_analysis_section_spans_section_version_id_analysis_sections')),
    sa.ForeignKeyConstraint(['span_id'], ['spans.span_id'], name=op.f('fk_analysis_section_spans_span_id_spans')),
    sa.PrimaryKeyConstraint('section_version_id', 'span_id', name=op.f('pk_analysis_section_spans')),
    sa.UniqueConstraint('section_version_id', 'ordinal', name=op.f('uq_analysis_section_spans_section_version_id'))
    )
    op.create_table('occurrences',
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('sentence_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('salience', sa.Enum('primary', 'secondary', name='occurrence_salience', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('content_source', sa.Enum('analysis_section', 'user_gloss', name='occurrence_content_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('section_revision', sa.Integer(), nullable=True),
    sa.Column('slot_bindings', sa.JSON(), nullable=True),
    sa.Column('source_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('extractor_model', sa.String(length=255), nullable=False),
    sa.Column('extractor_prompt_version', sa.String(length=255), nullable=False),
    sa.Column('user_marked_useful', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("content_source != 'analysis_section' OR (brief IS NOT NULL AND section_id IS NOT NULL AND section_revision IS NOT NULL)", name=op.f('ck_occurrences_analysis_section_content_reference')),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], name=op.f('fk_occurrences_extraction_run_id_extraction_runs')),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.kp_id'], name=op.f('fk_occurrences_kp_id_knowledge_points')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_occurrences_material_id_materials')),
    sa.ForeignKeyConstraint(['section_id', 'section_revision'], ['analysis_sections.section_id', 'analysis_sections.revision'], name='fk_occurrences_section_version'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_occurrences_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['source_analysis_id'], ['analyses.id'], name=op.f('fk_occurrences_source_analysis_id_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occurrences'))
    )
    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrences_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_kp_id'), ['kp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_sentence_id'), ['sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_source_analysis_id'), ['source_analysis_id'], unique=False)

    op.create_table('occurrence_spans',
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_occurrence_spans_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], name=op.f('fk_occurrence_spans_occurrence_id_occurrences')),
    sa.ForeignKeyConstraint(['span_id'], ['spans.span_id'], name=op.f('fk_occurrence_spans_span_id_spans')),
    sa.PrimaryKeyConstraint('occurrence_id', 'span_id', name=op.f('pk_occurrence_spans')),
    sa.UniqueConstraint('occurrence_id', 'ordinal', name=op.f('uq_occurrence_spans_occurrence_id'))
    )
    op.create_table('review_items',
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.kp_id'], name=op.f('fk_review_items_kp_id_knowledge_points')),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], name=op.f('fk_review_items_occurrence_id_occurrences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items')),
    sa.UniqueConstraint('kp_id', 'occurrence_id', name=op.f('uq_review_items_kp_id'))
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_kp_id'), ['kp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_occurrence_id'), ['occurrence_id'], unique=False)

    op.create_table('review_states',
    sa.Column('review_item_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('history', learningj.db.types.JsonListOf(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], name=op.f('fk_review_states_review_item_id_review_items')),
    sa.PrimaryKeyConstraint('review_item_id', name=op.f('pk_review_states')),
    sa.UniqueConstraint('review_item_id', name=op.f('uq_review_states_review_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_states')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_occurrence_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_kp_id'))

    op.drop_table('review_items')
    op.drop_table('occurrence_spans')
    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrences_source_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_occurrences_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_occurrences_material_id'))
        batch_op.drop_index(batch_op.f('ix_occurrences_kp_id'))
        batch_op.drop_index(batch_op.f('ix_occurrences_extraction_run_id'))

    op.drop_table('occurrences')
    op.drop_table('analysis_section_spans')
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_runs_analysis_id'))

    op.drop_table('extraction_runs')
    op.drop_table('annotation_spans')
    with op.batch_alter_table('analysis_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_sections_analysis_id'))

    op.drop_table('analysis_sections')
    with op.batch_alter_table('analysis_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_messages_analysis_id'))

    op.drop_table('analysis_messages')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spans_sentence_id'))

    op.drop_table('spans')
    with op.batch_alter_table('material_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_notes_material_id'))

    op.drop_table('material_notes')
    with op.batch_alter_table('dictionary_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_definitions_entry_id'))

    op.drop_table('dictionary_definitions')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_material_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('sidecars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sidecars_material_id'))

    op.drop_table('sidecars')
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_material_id'))

    op.drop_table('sentences')
    with op.batch_alter_table('known_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_known_evidence_lexeme_id'))

    op.drop_table('known_evidence')
    with op.batch_alter_table('dictionary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_entries_source_id'))
        batch_op.drop_index('ix_dictionary_entries_source_expression')

    op.drop_table('dictionary_entries')
    with op.batch_alter_table('dictionary_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_assets_source_id'))

    op.drop_table('dictionary_assets')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_material_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_kp_id'))

    op.drop_table('aliases')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_content_hash'))

    op.drop_table('materials')
    op.drop_table('lexemes')
    op.drop_table('learner_profile_notes')
    op.drop_table('knowledge_points')
    op.drop_table('dictionary_sources')
    with op.batch_alter_table('dictionary_import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_import_runs_archive_hash'))

    op.drop_table('dictionary_import_runs')
    # ### end Alembic commands ###
