/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/annotations/{annotation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Annotation
         * @description 删除个人批注数据（§0.1）：移除关联行并清理不再被引用的 Span。
         */
        delete: operations["delete_annotation_annotations__annotation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dictionaries */
        get: operations["list_dictionaries_dictionaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Dictionary
         * @description 导入 Yomitan ZIP：解析与资源落盘在事务外，发布是单个短事务。
         *
         *     同一 archive hash 的重复导入幂等：不重复写条目，仅记录重放运行
         *     （此时返回 200 而非 201）。
         */
        post: operations["import_dictionary_dictionaries_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Dictionary
         * @description 精确查找：expression 相等；带 reading 时限定该读音或空读音。
         *
         *     只读路径：查词不产生 KE（§9 不变量 8），无命中返回空 entries。
         */
        get: operations["lookup_dictionary_dictionaries_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Dictionary
         * @description 搜索框路径：精确匹配优先，FTS5 前缀匹配随后（派生投影，可重建）。
         */
        get: operations["search_dictionary_dictionaries_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/known-evidence/{evidence_id}/retractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retract Evidence
         * @description 撤回一条 KE（误点撤回）：追加保存来源历史；若撤回的是当前 known
         *     引用的 KE，同事务追加该作用域 clear。同键重试返回原结果（200）。
         */
        post: operations["retract_evidence_known_evidence__evidence_id__retractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lexemes/known-views/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Known Views
         * @description 阅读器目标集合批量读取（§11.1）：一次请求返回每个目标的作用域
         *     摘要与有效已知状态组合。unknown 压过导入；clear 回退其他来源。
         */
        post: operations["batch_known_views_lexemes_known_views_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lexemes/{lexeme_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Decision
         * @description 记录 known/unknown/clear 裁定；known 与其引用的 user_asserted KE
         *     同事务产生。同 operation_key 同输入幂等返回（200），异输入 409。
         */
        post: operations["create_decision_lexemes__lexeme_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lexemes/{lexeme_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evidence
         * @description 原始证据分页读取（§2.5）；撤回标记一并返回。
         */
        get: operations["list_evidence_lexemes__lexeme_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lexemes/{lexeme_id}/evidence-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence Summary
         * @description 按词证据摘要（投影与写事务同步更新；写后读一致）。
         */
        get: operations["get_evidence_summary_lexemes__lexeme_id__evidence_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_materials_get"];
        put?: never;
        /**
         * Create Material
         * @description Import txt, srt, vtt, or epub content and return its stable id.
         */
        post: operations["create_material_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Annotations
         * @description 列表检索：按文本（note/surface 子串）与时间筛选；spans 即跳回
         *     原文所需的定位数据。
         */
        get: operations["list_annotations_materials__material_id__annotations_get"];
        put?: never;
        /** Create Annotation */
        post: operations["create_annotation_materials__material_id__annotations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/lexeme-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material Lexeme Counts */
        get: operations["get_material_lexeme_counts_materials__material_id__lexeme_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/sentences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sentences */
        get: operations["list_sentences_materials__material_id__sentences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/sidecar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sidecar */
        get: operations["get_sidecar_materials__material_id__sidecar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/sidecar/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Sidecar
         * @description Re-derive the material's tokens as a new immutable generation.
         *
         *     Re-runs with an unchanged analyzer identity return the current
         *     generation unchanged; a changed candidate is published with its
         *     complete MaterialLexemeCount set and the pointer switch in one
         *     transaction, so the referenced payload is never overwritten.
         */
        post: operations["rebuild_sidecar_materials__material_id__sidecar_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentences/{sentence_id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentence Tokens
         * @description 当前已发布 sidecar 代次的句子 token 表（算法阅读器数据面）。
         *
         *     只读：token 表层/偏移/lexeme_id 来自不可变代次，响应携带完整版本
         *     来源；词典 provenance 按目标集一次批量查询。
         */
        get: operations["get_sentence_tokens_sentences__sentence_id__tokens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlgorithmTokenOut
         * @description 单个 token：表层、规范化形、POS、reading、code point 半开区间与
         *     确定性 lexeme_id（ADR-018）。偏移以 Unicode code point 计（§0）。
         */
        AlgorithmTokenOut: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Dictionary Source Ids */
            dictionary_source_ids: string[];
            /** Lexeme Id */
            lexeme_id: string;
            /** Normalized Form */
            normalized_form: string;
            /** Pos */
            pos: string;
            /** Reading Form */
            reading_form: string;
            /** Reading Source */
            reading_source: string;
            /** Surface */
            surface: string;
        };
        /** AnnotationCreateIn */
        AnnotationCreateIn: {
            /** Color */
            color?: string | null;
            /** Note */
            note?: string | null;
            /** Spans */
            spans: components["schemas"]["AnnotationSpanIn"][];
        };
        /** AnnotationOut */
        AnnotationOut: {
            /** Color */
            color?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Material Id */
            material_id: string;
            /** Note */
            note?: string | null;
            /** Spans */
            spans: components["schemas"]["AnnotationSpanOut"][];
        };
        /** AnnotationSpanIn */
        AnnotationSpanIn: {
            /** Sentence Id */
            sentence_id: string;
            /** Surface */
            surface: string;
        };
        /**
         * AnnotationSpanOut
         * @description Span 的 code point 半开区间由后端定位得出，切片恒等于 surface
         *     （§1 约束 1；§9 不变量 6 的生产行为面）。
         */
        AnnotationSpanOut: {
            /** Alignment Sidecar Id */
            alignment_sidecar_id?: string | null;
            /**
             * Alignment Status
             * @enum {string}
             */
            alignment_status: "aligned" | "partial" | "ambiguous" | "unaligned";
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Sentence Id */
            sentence_id: string;
            /** Span Id */
            span_id: string;
            /** Surface */
            surface: string;
            /** Token End */
            token_end?: number | null;
            /** Token Start */
            token_start?: number | null;
        };
        /** Body_create_material_materials_post */
        Body_create_material_materials_post: {
            /** File */
            file: string;
            /** Locator */
            locator?: string | null;
            /** @default external_reference */
            storage_mode: components["schemas"]["MaterialStorageMode"];
            /** Title */
            title?: string | null;
        };
        /** Body_import_dictionary_dictionaries_import_post */
        Body_import_dictionary_dictionaries_import_post: {
            /** File */
            file: string;
        };
        /** DecisionCreateIn */
        DecisionCreateIn: {
            /** Conjugated Form */
            conjugated_form?: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "known" | "unknown" | "clear";
            /** Expected Decision Seq */
            expected_decision_seq: number;
            /** Input Reading */
            input_reading?: string | null;
            /** Input Surface */
            input_surface: string;
            /** Material Id */
            material_id?: string | null;
            /** Operation Key */
            operation_key: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Conjugated Form */
            conjugated_form?: string | null;
            /** Created */
            created: boolean;
            /** Created At */
            created_at: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "known" | "unknown" | "clear";
            /** Decision Id */
            decision_id: string;
            /** Decision Seq */
            decision_seq: number;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Lexeme Id */
            lexeme_id: string;
            /** Operation Key */
            operation_key: string;
            /** Scope Form Key */
            scope_form_key: string;
        };
        /**
         * DictionaryDefinitionOut
         * @description 纯文本投影始终可用（资源缺失时定义仍可降级显示）；
         *     structured_content 保留原始富文本 payload。
         */
        DictionaryDefinitionOut: {
            /** Ordinal */
            ordinal: number;
            /** Plain Text */
            plain_text: string;
            /** Structured Content */
            structured_content?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DictionaryImportOut
         * @description `POST /dictionaries/import`：canonical source + 运行记录；同 archive
         *     hash 重放时 `idempotent_replay=true` 且不产生新条目。
         */
        DictionaryImportOut: {
            /** Idempotent Replay */
            idempotent_replay: boolean;
            /** Run Id */
            run_id: string;
            source: components["schemas"]["DictionarySourceOut"];
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
        };
        /**
         * DictionaryLookupOut
         * @description `GET /dictionaries/lookup`：精确查找；无命中时 entries 为空列表。
         */
        DictionaryLookupOut: {
            /** Entries */
            entries: components["schemas"]["LookupEntryOut"][];
            /** Expression */
            expression: string;
            /** Reading */
            reading?: string | null;
        };
        /**
         * DictionarySearchOut
         * @description `GET /dictionaries/search`：精确匹配优先，FTS5 前缀匹配随后。
         */
        DictionarySearchOut: {
            /** Entries */
            entries: components["schemas"]["LookupEntryOut"][];
            /** Query */
            query: string;
        };
        /** DictionarySourceOut */
        DictionarySourceOut: {
            /** Archive Hash */
            archive_hash: string;
            /** Display Name */
            display_name: string;
            /** Format */
            format: string;
            /** Id */
            id: string;
            /** Imported At */
            imported_at: string;
            /** License Metadata */
            license_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Schema Version */
            schema_version: string;
            /** Source Version */
            source_version: string;
        };
        /** EffectiveKnownOut */
        EffectiveKnownOut: {
            /** Basis */
            basis?: ("form_decision" | "lexeme_decision" | "import_evidence") | null;
            /** Decision Id */
            decision_id?: string | null;
            /** Evidence Id */
            evidence_id?: string | null;
            /** State */
            state?: ("known" | "unknown" | "clear") | null;
        };
        /** EvidenceItemOut */
        EvidenceItemOut: {
            /** Analyzer Dict Version */
            analyzer_dict_version: string;
            /** Confidence */
            confidence: number;
            /** Conjugated Form */
            conjugated_form?: string | null;
            /** Evidence Id */
            evidence_id: string;
            /** Input Reading */
            input_reading?: string | null;
            /** Input Surface */
            input_surface: string;
            /** Material Id */
            material_id?: string | null;
            /** Observed At */
            observed_at: string;
            /** Observed At Basis */
            observed_at_basis: string;
            /** Resolver Version */
            resolver_version: string;
            /** Retracted */
            retracted: boolean;
            /** Retraction Id */
            retraction_id?: string | null;
            /** Scope Form Key */
            scope_form_key: string;
            /** Source */
            source: string;
        };
        /**
         * EvidenceListOut
         * @description `GET /lexemes/{lexeme_id}/evidence`：原始证据分页读取（§2.5）。
         */
        EvidenceListOut: {
            /** Items */
            items: components["schemas"]["EvidenceItemOut"][];
            /** Lexeme Id */
            lexeme_id: string;
        };
        /**
         * EvidenceSummaryOut
         * @description `GET /lexemes/{lexeme_id}/evidence-summary`：按词证据摘要
         *     （可重建投影；写路径同事务更新，写后读一致）。
         */
        EvidenceSummaryOut: {
            /** Lexeme Id */
            lexeme_id: string;
            /** Projection Revision */
            projection_revision: number;
            /** Scopes */
            scopes: components["schemas"]["EvidenceSummaryScopeOut"][];
        };
        /** EvidenceSummaryScopeOut */
        EvidenceSummaryScopeOut: {
            /** Current Decision */
            current_decision?: ("known" | "unknown" | "clear") | null;
            /** Current Decision Id */
            current_decision_id?: string | null;
            /** Current Decision Seq */
            current_decision_seq?: number | null;
            /** Input Revision */
            input_revision: number;
            /** Known Evidence Id */
            known_evidence_id?: string | null;
            /** Known Rule Version */
            known_rule_version: string;
            /** Resolver Version */
            resolver_version: string;
            /** Scope Form Key */
            scope_form_key: string;
            /** Valid Source Counts */
            valid_source_counts: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnownViewIn */
        KnownViewIn: {
            /** Form */
            form?: string | null;
            /** Lexeme Id */
            lexeme_id: string;
        };
        /** KnownViewItemOut */
        KnownViewItemOut: {
            effective: components["schemas"]["EffectiveKnownOut"];
            /** Form */
            form?: string | null;
            form_scope?: components["schemas"]["EvidenceSummaryScopeOut"] | null;
            /** Lexeme Id */
            lexeme_id: string;
            lexeme_scope?: components["schemas"]["EvidenceSummaryScopeOut"] | null;
        };
        /**
         * KnownViewsBatchIn
         * @description 阅读器按当前页去重 Lexeme 集合批量取摘要（§11.1），不逐 token 请求。
         */
        KnownViewsBatchIn: {
            /** Items */
            items: components["schemas"]["KnownViewIn"][];
        };
        /** KnownViewsBatchOut */
        KnownViewsBatchOut: {
            /** Items */
            items: components["schemas"]["KnownViewItemOut"][];
            /** Known Rule Version */
            known_rule_version: string;
        };
        /** LookupEntryOut */
        LookupEntryOut: {
            /** Definitions */
            definitions: components["schemas"]["DictionaryDefinitionOut"][];
            /** Display Name */
            display_name: string;
            /** Expression */
            expression: string;
            /** Reading */
            reading?: string | null;
            /** Score */
            score: number;
            /** Sequence */
            sequence?: number | null;
            /** Source Id */
            source_id: string;
            /** Source Local Id */
            source_local_id: string;
            /** Source Version */
            source_version: string;
            /** Tags */
            tags: string[];
        };
        /** MaterialLexemeCountOut */
        MaterialLexemeCountOut: {
            /** Lexeme Id */
            lexeme_id: string;
            /** Token Count */
            token_count: number;
        };
        /**
         * MaterialLexemeCountsOut
         * @description One immutable sidecar generation's sparse material token counts.
         */
        MaterialLexemeCountsOut: {
            /** Counts */
            counts: components["schemas"]["MaterialLexemeCountOut"][];
            /** Material Id */
            material_id: string;
            /** Sidecar Generation Id */
            sidecar_generation_id: string;
        };
        /**
         * MaterialOut
         * @description `GET /materials` / `POST /materials` 的响应（data-model §8.1 +
         *     素材无关抽象 §8.2；`sentence_count` 是列表视图的读投影）。
         */
        MaterialOut: {
            /** Content Hash */
            content_hash: string;
            /** Copy Stored */
            copy_stored: boolean;
            /** Current Sidecar Id */
            current_sidecar_id?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "subtitle_video" | "subtitle_audio" | "text" | "epub";
            /** Locator */
            locator: string;
            /** Sentence Count */
            sentence_count: number;
            /** Source Sha256 */
            source_sha256?: string | null;
            /**
             * Storage Mode
             * @enum {string}
             */
            storage_mode: "external_reference" | "managed_copy";
            /** Title */
            title: string;
        };
        /**
         * MaterialStorageMode
         * @description 原始素材的持有方式（`data-model.md` §8.1）。
         * @enum {string}
         */
        MaterialStorageMode: "external_reference" | "managed_copy";
        /** RetractionCreateIn */
        RetractionCreateIn: {
            /** Operation Key */
            operation_key: string;
            /** Reason */
            reason?: string | null;
        };
        /** RetractionOut */
        RetractionOut: {
            /** Appended Clear */
            appended_clear: boolean;
            /** Created */
            created: boolean;
            /** Created At */
            created_at: string;
            /** Evidence Id */
            evidence_id: string;
            /** Operation Key */
            operation_key: string;
            /** Reason */
            reason?: string | null;
            /** Retraction Id */
            retraction_id: string;
        };
        /**
         * SentenceOut
         * @description `GET /materials/{material_id}/sentences` 的响应；`text` 与
         *     `anchor_payload` 的偏移均为 Unicode code point（data-model §0/§8.2）。
         */
        SentenceOut: {
            /** Anchor Payload */
            anchor_payload: {
                [key: string]: unknown;
            };
            /**
             * Anchor Type
             * @enum {string}
             */
            anchor_type: "subtitle" | "plain_text" | "epub";
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Material Id */
            material_id: string;
            /** Text */
            text: string;
            /** Time End */
            time_end?: number | null;
            /** Time Start */
            time_start?: number | null;
            /** Translation */
            translation?: string | null;
        };
        /**
         * SentenceTokensOut
         * @description `GET /sentences/{sentence_id}/tokens` 的响应：当前已发布 sidecar
         *     代次的 token 视图，带完整版本来源（§8.3 三个版本戳 + 代次 id）。
         */
        SentenceTokensOut: {
            /** Analyzer Dict Version */
            analyzer_dict_version: string;
            /** Dictionary Sources */
            dictionary_sources: components["schemas"]["TokenProvenanceOut"][];
            /** Material Id */
            material_id: string;
            /** Segmenter Version */
            segmenter_version: string;
            /** Sentence Id */
            sentence_id: string;
            /** Sidecar Generation Id */
            sidecar_generation_id: string;
            /** Tokenizer Version */
            tokenizer_version: string;
            /** Tokens */
            tokens: components["schemas"]["AlgorithmTokenOut"][];
        };
        /**
         * SidecarOut
         * @description `GET /materials/{material_id}/sidecar` 的响应；payload 为
         *     msgpack 解包后的分句/分词结果（data-model §8.3）。
         */
        SidecarOut: {
            /** Analyzer Dict Version */
            analyzer_dict_version: string;
            /** Content Hash */
            content_hash: string;
            /** Material Id */
            material_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Segmenter Version */
            segmenter_version: string;
            /** Sidecar Generation Id */
            sidecar_generation_id: string;
            /** Tokenizer Version */
            tokenizer_version: string;
        };
        /**
         * TokenProvenanceOut
         * @description 词典来源 provenance（§2.0：查询结果必须带 source/version）。
         */
        TokenProvenanceOut: {
            /** Display Name */
            display_name: string;
            /** Source Id */
            source_id: string;
            /** Source Version */
            source_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delete_annotation_annotations__annotation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                annotation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictionaries_dictionaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionarySourceOut"][];
                };
            };
        };
    };
    import_dictionary_dictionaries_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_dictionary_dictionaries_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_dictionary_dictionaries_lookup_get: {
        parameters: {
            query: {
                expression: string;
                reading?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryLookupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_dictionary_dictionaries_search_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionarySearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    retract_evidence_known_evidence__evidence_id__retractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetractionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetractionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_known_views_lexemes_known_views_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnownViewsBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnownViewsBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_decision_lexemes__lexeme_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lexeme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_lexemes__lexeme_id__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                lexeme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_summary_lexemes__lexeme_id__evidence_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lexeme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"][];
                };
            };
        };
    };
    create_material_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_material_materials_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_annotations_materials__material_id__annotations_get: {
        parameters: {
            query?: {
                q?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_annotation_materials__material_id__annotations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotationCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_lexeme_counts_materials__material_id__lexeme_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialLexemeCountsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sentences_materials__material_id__sentences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sidecar_materials__material_id__sidecar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidecarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_sidecar_materials__material_id__sidecar_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidecarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentence_tokens_sentences__sentence_id__tokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sentence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentenceTokensOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
